.\"	$OpenBSD$
.\"
.\" Copyright (c) 2026 Pawel Suchanecki <subdcc@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: July 10 2026 $
.Dt NEWFS_ZLFS 8
.Os
.Sh NAME
.Nm newfs_zlfs
.Nd construct a new ZLFS (zoned log-structured) file system
.Sh SYNOPSIS
.Nm
.Op Fl Nq
.Op Fl b Ar block-size
.Ar special
.Sh DESCRIPTION
.Nm
creates an experimental ZLFS file system on the zoned block device
.Ar special ,
which must be the raw whole-disk partition of a host-managed zoned
disk (SCSI ZBC or NVMe ZNS), for example
.Pa /dev/rsd1c
or simply
.Ar sd1c .
.Pp
The device's zones are enumerated with the
.Xr dkzone 4
interface and must be contiguous, uniformly sized sequential write
zones.
The first two zones are reserved for the ZLFS superblock log:
.Nm
resets both, writes the generation-0 superblock at the start of zone 0
and leaves zone 1 empty, then reads the superblock back to verify it.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl N
Dry run: print the derived file system geometry without writing
anything.
The device is opened read-only.
.It Fl b Ar block-size
The file system block size in bytes, a power of two between 512 and
65536 that is a multiple of the device sector size.
The default is 4096.
.It Fl q
Quiet: suppress the geometry summary.
.El
.Sh SEE ALSO
.Xr dkzone 4 ,
.Xr newfs 8
.Sh HISTORY
.Nm
first appeared in an experimental OpenBSD fork for zoned block device
support.
.Sh CAVEATS
ZLFS is under development and cannot be mounted yet.
Devices with conventional (non-write-pointer) zones are not yet
supported.
